repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      #- id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
  - repo: https://github.com/python-poetry/poetry
    rev: 1.2.0
    hooks:
      - id: poetry-check
  - repo: https://github.com/floatingpurr/sync_with_poetry
    rev: 0.3.0
    hooks:
      - id: sync_with_poetry
        args: [] # optional args
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.247"
    hooks:
      - id: ruff
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.0.1
    hooks:
      - id: mypy
        exclude: ^docs/conf.py
        additional_dependencies:
          - types-pkg-resources
          - types-requests
          - types-paramiko
          - types-pyOpenSSL
          - types-flask
          - types-waitress
          - pyModeS
          - pytest
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.0
    hooks:
      - id: prettier
