version: '3'

services:
  spark:
    image: docker.io/bitnami/spark:3.3
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8080:8080'
  spark-worker:
    image: docker.io/bitnami/spark:3.3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no

  # jupyterlab with pyspark
  pyspark:
    container_name: pyspark_notebook
    build:
      context: ./docker
      dockerfile: spark.Dockerfile
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    ports:
      - "8888:8888"
      # - "7077:7077"
    volumes:
      - ./data:/home/jovyan/traffic/data
      - ./tmp:/home/jovyan/traffic/tmp
